language: node_js
os:
- linux
node_js:
- '4'
- '6'
before_install:
- sudo apt-get update
- sudo apt-get install python
install:
- npm install
- cd ./test && npm install && cd ../
cache:
  directories:
  - node_modules
branches:
  only:
  - master
  - develop
sudo:
- true